# Generated by Django 2.2.1 on 2020-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daylog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('upperBand', models.FloatField()),
                ('lowerBand', models.FloatField()),
                ('bandWidth', models.FloatField()),
                ('rsi', models.FloatField()),
                ('upperSlope', models.FloatField()),
                ('realSlope', models.FloatField()),
                ('lowerSlope', models.FloatField()),
                ('upperI', models.FloatField()),
                ('realI', models.FloatField()),
                ('lowerI', models.FloatField()),
                ('action', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
            ],
        ),
    ]
