# Generated by Django 2.2.1 on 2020-09-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotTrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='quantity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
