# Generated by Django 2.2.1 on 2020-09-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotTrade', '0002_portfolio_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistorydb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfoliodb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=100)),
                ('buyingPrice', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('stockWorth', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Watchlistdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.FloatField()),
                ('investedCash', models.FloatField()),
                ('portfolioWorthCash', models.FloatField()),
                ('currentLeftCash', models.FloatField()),
                ('netWorthCash', models.FloatField()),
                ('orderHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.OrderHistorydb')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.Portfoliodb')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.Watchlistdb')),
            ],
        ),
    ]
