# Generated by Django 2.2.1 on 2020-09-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotTrade', '0003_orderhistorydb_portfoliodb_userdb_watchlistdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='orderHistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.OrderHistoryDb'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.PortfolioDb'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.WatchlistDb'),
        ),
    ]
