# Generated by Django 2.2.1 on 2020-09-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotTrade', '0006_auto_20200910_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistorydb',
            old_name='userId',
            new_name='userObject',
        ),
        migrations.RenameField(
            model_name='portfoliodb',
            old_name='userId',
            new_name='userObject',
        ),
        migrations.RenameField(
            model_name='watchlistdb',
            old_name='userId',
            new_name='userObject',
        ),
        migrations.AlterField(
            model_name='orderhistorydb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
        migrations.AlterField(
            model_name='portfoliodb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
        migrations.AlterField(
            model_name='watchlistdb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
    ]
