# Generated by Django 2.2.1 on 2020-09-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotTrade', '0007_auto_20200910_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliodb',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='portfoliodb',
            name='stockWorth',
        ),
        migrations.AlterField(
            model_name='orderhistorydb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
        migrations.AlterField(
            model_name='portfoliodb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
        migrations.AlterField(
            model_name='watchlistdb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
    ]
