# Generated by Django 2.2.1 on 2020-09-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotTrade', '0008_auto_20200911_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistorydb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
        migrations.AlterField(
            model_name='portfoliodb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='currentLeftCash',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='investedCash',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='netWorthCash',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='portfolioWorthCash',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='watchlistdb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
    ]
