# Generated by Django 3.0.3 on 2020-09-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotTrade', '0009_auto_20200912_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPriceDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=100)),
                ('currentPrice', models.FloatField(null=True)),
                ('prevClosePrice', models.FloatField(null=True)),
                ('percentChange', models.FloatField(null=True)),
                ('priceChange', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfoliodb',
            name='profit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliodb',
            name='stockWorth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderhistorydb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
        migrations.AlterField(
            model_name='portfoliodb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='mobile',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='watchlistdb',
            name='userObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTrade.UserDb'),
        ),
        migrations.AddField(
            model_name='portfoliodb',
            name='currentPrice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BotTrade.CurrentPriceDb'),
        ),
        migrations.AddField(
            model_name='watchlistdb',
            name='currentPrice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BotTrade.CurrentPriceDb'),
        ),
    ]
